### ISSUE TITLE
Invalid Redirect URI

### ISSUE THREAD

**Issue by sammyspills** [pawelad/pymonzo#24]
When MonzoAPI() is called with keyword arguments (i.e. not using env variables) I get the following response:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pymonzo/monzo_api.py", line 76, in __init__
    self._token = self._get_oauth_token()
  File "/usr/local/lib/python2.7/dist-packages/pymonzo/monzo_api.py", line 155, in _get_oauth_token
    client_secret=self._client_secret,
  File "/usr/local/lib/python2.7/dist-packages/requests_oauthlib/oauth2_session.py", line 244, in fetch_token
    self._client.parse_request_body_response(r.text, scope=self.scope)
  File "/usr/local/lib/python2.7/dist-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 411, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
  File "/usr/local/lib/python2.7/dist-packages/oauthlib/oauth2/rfc6749/parameters.py", line 379, in parse_token_response
    validate_token_parameters(params)
  File "/usr/local/lib/python2.7/dist-packages/oauthlib/oauth2/rfc6749/parameters.py", line 386, in validate_token_parameters
    raise_from_error(params.get('error'), params)
  File "/usr/local/lib/python2.7/dist-packages/oauthlib/oauth2/rfc6749/errors.py", line 415, in raise_from_error
    raise cls(**kwargs)
oauthlib.oauth2.rfc6749.errors.InvalidClientIdError: (invalid_request) Invalid redirect URI

```
I'm assuming this is to do with how I have configured the client on the Monzo dev portal, but I can't see what's wrong with it?

**Comment by sammyspills** [comment]
Sorry, my bad, fixed this by making absolutely sure the redirect links matched in every part of the app and all the app logic worked... If anyone sees this and is having the same issue, make sure the links are the same in every place they are used. Copy-paste is your friend (duh, I'm an idiot...)
